name: ambisis_challenge
description: "Desafio da seleção para Desenvolvedor Flutter na Ambisis"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  sqflite: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
